# NumPy Tutorial

In this tutorial, we will cover various aspects of NumPy, including:

1. What is a matrix and how to create one in NumPy
2. How does reshaping work in NumPy
3. What does the size operator do
4. What does the -1 do when it comes to reshaping
5. What does flatten do
6. How does one index a NumPy matrix two-dimensionally
7. How does one aggregate over the different dimensions
8. How does one perform matrix multiplication

Let's get started!


## 1. What is a matrix and how to create one in NumPy

A matrix is a two-dimensional array of numbers arranged in rows and columns. We can create a matrix in NumPy using the `np.array()` function.

Let's create a sample matrix in NumPy.

In [5]:
# Importing necessary library
import numpy as np

# Creating a sample matrix
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Displaying the matrix
print("Sample Matrix:")
print(data)
# notice the matrix has a single type for all its elements
print(data.dtype)


Sample Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64


## 2. How does reshaping work in NumPy

Reshaping allows us to change the shape (dimensions) of an array. We can reshape an array using the `np.reshape()` function.

Let's reshape our sample matrix.

In [10]:
# Reshaping the matrix
reshaped_data = np.reshape(data, (1, 9))

# Displaying the reshaped matrix
print("Reshaped Matrix:")
print(reshaped_data)

Reshaped Matrix:
[[1 2 3 4 5 6 7 8 9]]


## 3. What does the size operator do

The size operator returns the number of elements in an array. We can use the `size` attribute of the NumPy array.

Let's find the size of our sample matrix.

In [14]:
print(data.size)
print(data.shape)

9
(3, 3)


## 4. What does the -1 do when it comes to reshaping

When we use `-1` in reshaping, NumPy automatically calculates the dimension based on the other specified dimensions. It infers the unknown dimension.

Let's reshape our sample matrix using `-1`.

In [27]:
# Reshaping the matrix using -1
reshaped_data_negative = np.reshape(data, (1, -1))

# Displaying the reshaped matrix with -1
print("Reshaped Matrix with -1:")
print(reshaped_data_negative)
print(reshaped_data_negative.shape)
# this breaks: cannot reshape array of size 9 into shape (2, newaxis)
# reshaped = np.reshape(data, (2, -1))
# print(reshaped)

# this works and creates a list. The shape is different!
reshaped_single = np.reshape(data, (-1, ))
print(reshaped_single)
print(reshaped_single.shape)

# the semantic to access one element is different, mor on that later
print(reshaped_data_negative[0][2])
print(reshaped_single[2])


Reshaped Matrix with -1:
[[1 2 3 4 5 6 7 8 9]]
(1, 9)
[1 2 3 4 5 6 7 8 9]
(9,)
3
3


## 5. What does flatten do

Flattening converts a multi-dimensional array into a one-dimensional array. We can use the `flatten()` method in NumPy to flatten an array.

Let's flatten our sample matrix.

In [26]:
# Flattening the matrix
flattened_data = data.flatten()

# Displaying the flattened matrix
print("Flattened Matrix:")
print(flattened_data)



Flattened Matrix:
[1 2 3 4 5 6 7 8 9]


## 6. How does one index a NumPy matrix two-dimensionally

We can index a NumPy matrix using row and column indices. The syntax for two-dimensional indexing is `array[row_index, column_index]`.

Let's index our sample matrix two-dimensionally.

In [28]:
# Indexing a NumPy matrix two-dimensionally
element = data[1, 2]  # Accessing element at row 1, column 2

# Displaying the indexed element
print("Element at index (1, 2):", element)

Element at index (1, 2): 6


## 7. How does one aggregate over the different dimensions

We can aggregate over different dimensions (e.g., rows, columns) of a NumPy matrix using functions like `np.sum()`, `np.mean()`, `np.max()`, etc.

Let's perform aggregation over rows and columns of our sample matrix.

In [31]:
# Aggregating over rows and columns
row_sum = np.sum(data, axis=1)  # Sum over rows
col_max = np.max(data, axis=0)  # Max over columns

# Displaying the aggregated results
print("Sum over Rows:", row_sum)
print("Max over Columns:", col_max)

print("Grand Sum (the default): ", np.sum(data))

Sum over Rows: [ 6 15 24]
Max over Columns: [7 8 9]
Grand Sum (the default):  45


## 8. How does one perform matrix multiplication

Matrix multiplication can be performed using the `np.dot()` function in NumPy or the `@` operator.

Let's perform matrix multiplication with our sample matrix.

In [37]:
# Creating another sample matrix
other_data = np.array([[1, 0],
                       [0, 1],
                       [1, 1]])

# Performing matrix multiplication
result = np.dot(data, other_data)

# Displaying the result of matrix multiplication
print("Result of Matrix Multiplication:")
print(result)

print(data @ other_data)
# unlike scalar multiplication matrix multiplication is NOT commutative
# in fact, in this case it's not even possible
# ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)
# not the clearest error, but it means the matrixes need to have shapes (x, K) and (K, y), with K being the same
# print(other_data @ data)



Result of Matrix Multiplication:
[[ 4  5]
 [10 11]
 [16 17]]
[[ 4  5]
 [10 11]
 [16 17]]
